version: "3"

services:
  data-lake:
    build:
      context: .
      dockerfile: data-lake/Dockerfile
    hostname: jazero-data-lake
    networks:
      jazero_network:
        ipv4_address: 172.30.0.5
      hdfs_network:
    ports:
      - "8081:8081"
    volumes:
      - ./knowledge-graph/neo4j/:/home/knowledge-graph/neo4j
      - ./index/:/index
      - ./logs/:/logs
      - ./.tables/:/srv/storage
  entity-linker:
    build:
      context: .
      dockerfile: entity-linker/Dockerfile
    hostname: jazero-entity-linker
    networks:
      jazero_network:
        ipv4_address: 172.30.0.4
    ports:
      - "8082:8082"
    volumes:
      - ./knowledge-graph/neo4j/:/home/knowledge-graph/neo4j
      - ./index/:/index
      - ./kg:/home/kg
  ekg-manager:
    build:
      context: .
      dockerfile: knowledge-graph/Dockerfile
    hostname: jazero-ekg
    networks:
      jazero_network:
        ipv4_address: 172.30.0.3
    ports:
      - "8083:8083"
    volumes:
      - ./knowledge-graph/neo4j/:/scripts
      - ./index/:/index
      - ./kg:/home/kg
  embeddings:
    image: postgres
    container_name: jazero_pg
    hostname: jazero-hostname
    networks:
      jazero_network:
        ipv4_address: 172.30.0.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jazero
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=embeddings
  neo4j:
    image: neo4j:4.1.4
    container_name: jazero_neo4j
    hostname: jazero-neo4j
    networks:
      jazero_network:
        ipv4_address: 172.30.0.6
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./index/neo4j/data:/var/lib/neo4j/data
      - ./index/neo4j/plugins:/var/lib/neo4j/plugins
      - ./index/neo4j/import:/var/lib/neo4j/import
      - ./index/mappings/:/index/mappings
      - ./kg:/kg
      - ./knowledge-graph/neo4j/:/scripts
    environment:
      - NEO4J_AUTH=neo4j/jazero_admin
      - NEO4JLABS_PLUGINS='["apoc", "n10s"]'
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use_neo4j_config=false
networks:
  jazero_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
  hdfs_network:
    external: true
