version: "3"

services:
  web:
    container_name: jazero
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - jazero_web
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      web:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - jazero_web
    links:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  jazero_web:
    driver: bridge
